theme: jekyll-theme-cayman
title: Pulkit Khandelwal
email: pulkit.khandelwal@mail.mcgill.ca
author: Pulkit Khandelwal

# Social icons
github_username: pulkit-khandelwal
bitbucket_username:
stackoverflow_id:
twitter_username: pulkittweet
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
